class EmergencyContact {
  final String? id; // Emergency contact ID (can be auto-generated by Firestore)
  final String userId; // ID of the user associated with the emergency contact
  final String name; // Name of the emergency contact
  final String contactNumber; // Contact number of the emergency contact
  final String relation; // Relation to the user

  EmergencyContact({
    this.id,
    required this.userId,
    required this.name,
    required this.contactNumber,
    required this.relation,
  });

  // Factory method to create an EmergencyContact from Firestore data
  factory EmergencyContact.fromMap(String id, Map<String, dynamic> data) {
    return EmergencyContact(
      id: id,
      userId: data['userId'] as String,
      name: data['name'] as String,
      contactNumber: data['contactNumber'] as String,
      relation: data['relation'] as String,
    );
  }

  // Convert an EmergencyContact to a map for Firestore
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'name': name,
      'contactNumber': contactNumber,
      'relation': relation,
    };
  }

  // Copy with method to create a modified instance
  EmergencyContact copyWith({
    String? id,
    String? userId,
    String? name,
    String? contactNumber,
    String? relation,
  }) {
    return EmergencyContact(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      contactNumber: contactNumber ?? this.contactNumber,
      relation: relation ?? this.relation,
    );
  }

  @override
  String toString() {
    return 'EmergencyContact{id: $id, userId: $userId, name: $name, contactNumber: $contactNumber, relation: $relation}';
  }
}
