import 'package:cloud_firestore/cloud_firestore.dart';

class RouteModel {
  final String? id; // Route ID (can be auto-generated by Firestore)
  final String groupId; // ID of the group this route belongs to
  final String heading; // Heading/title of the stop
  final String typeOfStop; // Type/category of the stop
  final DateTime startingTime; // Scheduled time for the stop
  final DateTime endingTime; // Duration spent at the stop
  final String startingFrom; // Address/location
  final String description; // Description of the stop
  final String endingAt; // Purpose of the stop
  final DateTime createdAt; // Timestamp of when the route was created
  final String createdBy; // ID of the manager who created the route
  final int orderIndex; // Position of the route in the list

  RouteModel({
    this.id,
    required this.groupId,
    required this.heading,
    required this.typeOfStop,
    required this.startingTime,
    required this.endingTime,
    required this.startingFrom,
    required this.description,
    required this.endingAt,
    required this.createdAt,
    required this.createdBy,
    required this.orderIndex,
  });

  // Factory method to create a RouteModel from Firestore data
  factory RouteModel.fromMap(String id, Map<String, dynamic> data) {
    return RouteModel(
      id: id,
      groupId: data['groupId'] as String,
      heading: data['heading'] as String,
      typeOfStop: data['typeOfStop'] as String,
      startingTime: (data['startingTime'] as Timestamp).toDate(),
      endingTime: (data['endingTime'] as Timestamp).toDate(),
      startingFrom: data['startingFrom'] as String,
      description: data['description'] as String,
      endingAt: data['endingAt'] as String,
      createdAt: (data['createdAt'] as Timestamp).toDate(),
      createdBy: data['createdBy'] as String,
      orderIndex: data['orderIndex'] as int,
    );
  }

  // Convert a RouteModel to a map for Firestore
  Map<String, dynamic> toMap() {
    return {
      'groupId': groupId,
      'heading': heading,
      'typeOfStop': typeOfStop,
      'startingTime': Timestamp.fromDate(startingTime),
      'endingTime': Timestamp.fromDate(endingTime),
      'startingFrom': startingFrom,
      'description': description,
      'endingAt': endingAt,
      'createdAt': Timestamp.fromDate(createdAt),
      'createdBy': createdBy,
      'orderIndex': orderIndex,
    };
  }
}
